export const PROTOCOLS = [
  {
    name: "以太网",
    key: "ethernet",
    fields: [
      { label: "目的MAC地址", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { label: "源MAC地址", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "类型", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { label: "Payload / 数据", key: "data", type: "text", placeholder: "00", maxLength: 750 },
    ],
  },
  {
    name: "ARP",
    key: "arp",
    fields: [
      { label: "目的MAC地址", key: "dst_mac", type: "text", placeholder: "FF:FF:FF:FF:FF:FF", maxLength: 17 },
      { label: "源MAC地址", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "类型", key: "ether_type", type: "text", placeholder: "0806", maxLength: 4 },
      { label: "硬件类型", key: "hwType", type: "number", placeholder: "0001", maxLength: 4 },
      { label: "协议类型", key: "protoType", type: "text", placeholder: "0800", maxLength: 4 },
      { label: "操作码", key: "opcode", type: "number", placeholder: "0001", maxLength: 4 },
      { label: "发送方MAC", key: "srcMac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "发送方IP", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { label: "目标MAC", key: "dstMac", type: "text", placeholder: "00:00:00:00:00:00", maxLength: 17 },
      { label: "目标IP", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { label: "Payload / 数据", key: "data", type: "text", placeholder: "00", maxLength: 256 },
    ],
  },
  {
    name: "IPv4",
    key: "ipv4",
    fields: [
      { label: "目的MAC地址", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { label: "源MAC地址", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "以太网类型", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { label: "版本", key: "version", type: "number", placeholder: "4", maxLength: 1 },
      { label: "头部长度", key: "ihl", type: "number", placeholder: "5", maxLength: 1 },
      { label: "服务类型", key: "tos", type: "number", placeholder: "0", maxLength: 3 },
      { label: "总长度", key: "total_length", type: "number", placeholder: "0", maxLength: 5 },
      { label: "标识符", key: "identification", type: "number", placeholder: "0", maxLength: 5 },
      { label: "标志位", key: "flags", type: "number", placeholder: "2", maxLength: 1 },
      { label: "片偏移", key: "fragment_offset", type: "number", placeholder: "0", maxLength: 4 },
      { label: "生存时间(TTL)", key: "ttl", type: "number", placeholder: "64", maxLength: 3 },
      { label: "协议", key: "protocol", type: "number", placeholder: "6", maxLength: 3 },
      { label: "头部校验和", key: "header_checksum", type: "number", placeholder: "0", maxLength: 5 },
      { label: "源IP地址", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { label: "目的IP地址", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { label: "Payload / 数据", key: "data", type: "text", placeholder: "00", maxLength: 1460 },
    ],
  },
  {
    name: "UDP",
    key: "udp",
    fields: [
      { label: "目的MAC地址", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { label: "源MAC地址", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "以太网类型", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { label: "源IP地址", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { label: "目的IP地址", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { label: "源端口", key: "srcPort", type: "number", placeholder: "12345", maxLength: 5 },
      { label: "目的端口", key: "dstPort", type: "number", placeholder: "53", maxLength: 5 },
      { label: "长度", key: "length", type: "number", placeholder: "0", maxLength: 5 },
      { label: "校验和", key: "checksum", type: "number", placeholder: "0", maxLength: 5 },
      { label: "Payload / 数据", key: "data", type: "text", placeholder: "hello", maxLength: 1472 },
    ],
  },
  {
    name: "TCP",
    key: "tcp",
    fields: [
      { label: "目的MAC地址", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { label: "源MAC地址", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { label: "以太网类型", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { label: "源IP地址", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { label: "目的IP地址", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { label: "源端口", key: "srcPort", type: "number", placeholder: "12345", maxLength: 5 },
      { label: "目的端口", key: "dstPort", type: "number", placeholder: "80", maxLength: 5 },
      { label: "序列号", key: "seq", type: "number", placeholder: "0", maxLength: 10 },
      { label: "确认号", key: "ack", type: "number", placeholder: "0", maxLength: 10 },
      { label: "数据偏移", key: "data_offset", type: "number", placeholder: "5", maxLength: 2 },
      { label: "保留位", key: "reserved", type: "number", placeholder: "0", maxLength: 1 },
      { label: "URG标志", key: "flag_urg", type: "number", placeholder: "0", maxLength: 1 },
      { label: "ACK标志", key: "flag_ack", type: "number", placeholder: "0", maxLength: 1 },
      { label: "PSH标志", key: "flag_psh", type: "number", placeholder: "0", maxLength: 1 },
      { label: "RST标志", key: "flag_rst", type: "number", placeholder: "0", maxLength: 1 },
      { label: "SYN标志", key: "flag_syn", type: "number", placeholder: "1", maxLength: 1 },
      { label: "FIN标志", key: "flag_fin", type: "number", placeholder: "0", maxLength: 1 },
      { label: "窗口大小", key: "window_size", type: "number", placeholder: "8192", maxLength: 5 },
      { label: "校验和", key: "checksum", type: "number", placeholder: "0", maxLength: 5 },
      { label: "紧急指针", key: "urgent_pointer", type: "number", placeholder: "0", maxLength: 5 },
      { label: "Payload / 数据", key: "data", type: "text", placeholder: "hello", maxLength: 1460 },
    ],
  },
]; 