export const PROTOCOLS = [
  {
    nameKey: "protocols.ethernet",
    key: "ethernet",
    fields: [
      { labelKey: "labels.dst_mac", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { labelKey: "labels.src_mac", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.ether_type", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { labelKey: "labels.data", key: "data", type: "text", placeholder: "00", maxLength: 750 },
    ],
  },
  {
    nameKey: "protocols.arp",
    key: "arp",
    fields: [
      { labelKey: "labels.dst_mac", key: "dst_mac", type: "text", placeholder: "FF:FF:FF:FF:FF:FF", maxLength: 17 },
      { labelKey: "labels.src_mac", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.ether_type", key: "ether_type", type: "text", placeholder: "0806", maxLength: 4 },
      { labelKey: "labels.hwType", key: "hwType", type: "number", placeholder: "0001", maxLength: 4 },
      { labelKey: "labels.protoType", key: "protoType", type: "text", placeholder: "0800", maxLength: 4 },
      { labelKey: "labels.opcode", key: "opcode", type: "number", placeholder: "0001", maxLength: 4 },
      { labelKey: "labels.srcMac", key: "srcMac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.srcIp", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { labelKey: "labels.dstMac", key: "dstMac", type: "text", placeholder: "00:00:00:00:00:00", maxLength: 17 },
      { labelKey: "labels.dstIp", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { labelKey: "labels.data", key: "data", type: "text", placeholder: "00", maxLength: 256 },
    ],
  },
  {
    nameKey: "protocols.ipv4",
    key: "ipv4",
    fields: [
      { labelKey: "labels.dst_mac", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { labelKey: "labels.src_mac", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.ether_type", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { labelKey: "labels.version", key: "version", type: "number", placeholder: "4", maxLength: 1 },
      { labelKey: "labels.ihl", key: "ihl", type: "number", placeholder: "5", maxLength: 1 },
      { labelKey: "labels.tos", key: "tos", type: "number", placeholder: "0", maxLength: 3 },
      { labelKey: "labels.total_length", key: "total_length", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.identification", key: "identification", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.flags", key: "flags", type: "number", placeholder: "2", maxLength: 1 },
      { labelKey: "labels.fragment_offset", key: "fragment_offset", type: "number", placeholder: "0", maxLength: 4 },
      { labelKey: "labels.ttl", key: "ttl", type: "number", placeholder: "64", maxLength: 3 },
      { labelKey: "labels.protocol", key: "protocol", type: "number", placeholder: "6", maxLength: 3 },
      { labelKey: "labels.header_checksum", key: "header_checksum", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.srcIp", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { labelKey: "labels.dstIp", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { labelKey: "labels.data", key: "data", type: "text", placeholder: "00", maxLength: 1460 },
    ],
  },
  {
    nameKey: "protocols.udp",
    key: "udp",
    fields: [
      { labelKey: "labels.dst_mac", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { labelKey: "labels.src_mac", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.ether_type", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { labelKey: "labels.srcIp", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { labelKey: "labels.dstIp", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { labelKey: "labels.srcPort", key: "srcPort", type: "number", placeholder: "12345", maxLength: 5 },
      { labelKey: "labels.dstPort", key: "dstPort", type: "number", placeholder: "53", maxLength: 5 },
      { labelKey: "labels.length", key: "length", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.checksum", key: "checksum", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.data", key: "data", type: "text", placeholder: "hello", maxLength: 1472 },
    ],
  },
  {
    nameKey: "protocols.tcp",
    key: "tcp",
    fields: [
      { labelKey: "labels.dst_mac", key: "dst_mac", type: "text", placeholder: "AA:BB:CC:DD:EE:FF", maxLength: 17 },
      { labelKey: "labels.src_mac", key: "src_mac", type: "text", placeholder: "__LOCAL_MAC__", maxLength: 17 },
      { labelKey: "labels.ether_type", key: "ether_type", type: "text", placeholder: "0800", maxLength: 4 },
      { labelKey: "labels.srcIp", key: "srcIp", type: "text", placeholder: "__LOCAL_IP__", maxLength: 15 },
      { labelKey: "labels.dstIp", key: "dstIp", type: "text", placeholder: "192.168.1.2", maxLength: 15 },
      { labelKey: "labels.srcPort", key: "srcPort", type: "number", placeholder: "12345", maxLength: 5 },
      { labelKey: "labels.dstPort", key: "dstPort", type: "number", placeholder: "80", maxLength: 5 },
      { labelKey: "labels.seq", key: "seq", type: "number", placeholder: "0", maxLength: 10 },
      { labelKey: "labels.ack", key: "ack", type: "number", placeholder: "0", maxLength: 10 },
      { labelKey: "labels.data_offset", key: "data_offset", type: "number", placeholder: "5", maxLength: 2 },
      { labelKey: "labels.reserved", key: "reserved", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.flag_urg", key: "flag_urg", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.flag_ack", key: "flag_ack", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.flag_psh", key: "flag_psh", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.flag_rst", key: "flag_rst", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.flag_syn", key: "flag_syn", type: "number", placeholder: "1", maxLength: 1 },
      { labelKey: "labels.flag_fin", key: "flag_fin", type: "number", placeholder: "0", maxLength: 1 },
      { labelKey: "labels.window_size", key: "window_size", type: "number", placeholder: "8192", maxLength: 5 },
      { labelKey: "labels.checksum", key: "checksum", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.urgent_pointer", key: "urgent_pointer", type: "number", placeholder: "0", maxLength: 5 },
      { labelKey: "labels.data", key: "data", type: "text", placeholder: "hello", maxLength: 1460 },
    ],
  },
]; 