
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 构建完整以太网帧并返回大写 hex 预览。
 * 
 * 按 `spec.protocol` 派发到对应协议 builder；任何字段解析失败返回 `Err(String)`。
 * 
 * 命名注：v1 在 `lib.rs` 已注册了一个收 `serde_json::Value` 的 `build_packet_preview`，
 * 两者 Tauri 命令名不能撞，故 v2 注册为 `build_packet_preview_v2`（v1 不动，只增不减）。
 * M1 重写完成、前端切到强类型后，旧命令会随 v1 一并退役。
 */
async buildPacketPreviewV2(spec: PacketSpec) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("build_packet_preview_v2", { spec }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 枚举本机网卡（v2）。
 */
async listInterfacesV2() : Promise<Result<InterfaceInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_interfaces_v2") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 单发：构建强类型 spec 为完整帧，经指定网卡用 pcap 发出。
 */
async sendPacketV2(spec: PacketSpec, interfaceName: string) : Promise<Result<SendReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_packet_v2", { spec, interfaceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 启动批量发送（v2）。stop_condition: "manual"|"duration"|"count"，stop_value 为秒数或包数。
 */
async startBatchSendV2(spec: PacketSpec, interfaceName: string, frequency: number, stopCondition: string, stopValue: number) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_batch_send_v2", { spec, interfaceName, frequency, stopCondition, stopValue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 查询批量任务状态。
 */
async getBatchStatusV2(taskId: string) : Promise<BatchStatus | null> {
    return await TAURI_INVOKE("get_batch_status_v2", { taskId });
},
/**
 * 停止批量任务。
 */
async stopBatchSendV2(taskId: string) : Promise<boolean> {
    return await TAURI_INVOKE("stop_batch_send_v2", { taskId });
},
/**
 * 启动网口嗅探（v2）。启动即验证网卡可打开，失败 Err；幂等：已在跑先停。
 * 统计经 `capture://stats` event 每 250ms 主动推送，包列表用 `get_captured_packets_v2` 拉取。
 */
async startCaptureV2(interfaceName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_capture_v2", { interfaceName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 停止网口嗅探（v2）。
 */
async stopCaptureV2() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_capture_v2") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 查询当前捕获统计快照（v2）。无捕获时返回零值快照。
 */
async getCaptureStatsV2() : Promise<CaptureStats | null> {
    return await TAURI_INVOKE("get_capture_stats_v2");
},
/**
 * 拉取最新捕获的包（v2，最新在前）。默认 100。
 */
async getCapturedPacketsV2(maxCount: number | null) : Promise<CapturedPacket[]> {
    return await TAURI_INVOKE("get_captured_packets_v2", { maxCount });
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * ARP 帧规格。以太网头部 + ARP 报文全部字段。
 * 注意：以太网层 src/dst MAC 与 ARP 层 sender/target MAC 分开建模——二者可不同。
 */
export type ArpSpec = { dst_mac: string; src_mac: string; hw_type: number; proto_type: number; hw_size: number; proto_size: number; opcode: number; sender_mac: string; sender_ip: string; target_mac: string; target_ip: string; payload_hex: string }
export type BatchStatus = { task_id: string; start_time: number; sent_count: number; target_speed: number; running: boolean; completed: boolean }
/**
 * 捕获统计（真值，全量累计 + 实时速率）。经 event 推送给前端。
 */
export type CaptureStats = { total_packets: number; total_bytes: number; 
/**
 * 实时包速率（最近一个完整秒桶的包数）。
 */
pps: number; 
/**
 * 实时字节速率（最近一个完整秒桶的字节数）。
 */
bps: number; tcp: number; udp: number; arp: number; icmp: number; other: number; 
/**
 * 因包列表缓冲满被丢弃的包数（不影响统计真值，仅影响前端可见列表）。
 */
dropped_for_display: number }
/**
 * 单个解析后的包，供前端列表展示。
 */
export type CapturedPacket = { id: string; 
/**
 * 包头时间戳（毫秒，UNIX epoch）。来自 pcap `header.ts`，非本地时钟。
 */
timestamp_ms: number; protocol: string; src_mac: string; dst_mac: string; src_ip: string | null; dst_ip: string | null; src_port: number | null; dst_port: number | null; size: number; info: string }
/**
 * 以太网帧规格。字段命名为单一事实来源，经 specta 自动生成同名 TS 类型。
 */
export type EthernetSpec = { dst_mac: string; src_mac: string; ether_type: number; payload_hex: string }
/**
 * ICMP 帧规格。IPv4 层同 TcpSpec 用固定默认，仅暴露 ttl/identification。
 */
export type IcmpSpec = { dst_mac: string; src_mac: string; ttl: number; identification: number; src_ip: string; dst_ip: string; icmp_type: number; icmp_code: number; checksum: number | null; 
/**
 * ICMP 头第 5-8 字节。Echo 时 = (identifier << 16) | sequence。
 */
rest_of_header: number; payload_hex: string }
export type InterfaceInfo = { name: string; description: string | null; mac: string | null; addresses: string[] }
/**
 * IPv4 帧规格。以太网头 + IPv4 头全部字段 + payload。
 * `checksum: None`/Some(0) → 自动计算；Some(非0) → 用用户值（用于故意造错包）。
 */
export type Ipv4Spec = { dst_mac: string; src_mac: string; version: number; ihl: number; 
/**
 * DSCP(6) + ECN(2) 合并为一字节（即旧 TOS 字段）。
 */
dscp_ecn: number; identification: number; 
/**
 * 3 位标志（bit2=保留0, bit1=DF, bit0=MF），放低 3 位。
 */
flags: number; fragment_offset: number; ttl: number; protocol: number; checksum: number | null; src_ip: string; dst_ip: string; payload_hex: string }
/**
 * 顶层协议派发枚举。`kind` 字段做 serde 标签，前端按 `{ kind: "tcp", ... }`
 * 发来，反序列化直接落到对应变体。每个变体携带构建**完整以太网帧**所需的全部字段。
 * 注意：标签用 `kind` 而非 `protocol`，因为 `Ipv4Spec` 已有名为 `protocol` 的
 * IP 协议号字段，撞名会让 TS 联合类型坍缩为 never。
 */
export type PacketSpec = ({ kind: "ethernet" } & EthernetSpec) | ({ kind: "arp" } & ArpSpec) | ({ kind: "ipv4" } & Ipv4Spec) | ({ kind: "tcp" } & TcpSpec) | ({ kind: "udp" } & UdpSpec) | ({ kind: "icmp" } & IcmpSpec)
/**
 * 单发结果：发出的字节数 + 出口网卡名。
 */
export type SendReport = { bytes: number; interface: string }
/**
 * TCP 帧规格。以太网头 + IPv4 头(常用子集) + TCP 头(20B, 无选项) + payload。
 * IPv4 层用固定默认（version 4 / ihl 5 / dscp 0 / flags DF / offset 0 / 自动算 IP 校验和），
 * 仅暴露 ttl 与 identification 供调整；如需精细控制 IPv4 头请直接用 Ipv4Spec。
 */
export type TcpSpec = { dst_mac: string; src_mac: string; ttl: number; identification: number; src_ip: string; dst_ip: string; src_port: number; dst_port: number; seq: number; ack: number; 
/**
 * 数据偏移（以 4 字节为单位），无选项时为 5。会被 clamp 到 [5,15]。
 */
data_offset: number; flag_urg: boolean; flag_ack: boolean; flag_psh: boolean; flag_rst: boolean; flag_syn: boolean; flag_fin: boolean; window_size: number; checksum: number | null; urgent_pointer: number; payload_hex: string }
/**
 * UDP 帧规格。IPv4 层同 TcpSpec 用固定默认，仅暴露 ttl/identification。
 */
export type UdpSpec = { dst_mac: string; src_mac: string; ttl: number; identification: number; src_ip: string; dst_ip: string; src_port: number; dst_port: number; checksum: number | null; payload_hex: string }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
